name: 'CI'
description: 'Call perl-test.yml on every push and pull request'

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  call-perl-test:
    uses: ryoskzypu/github_workflows/.github/workflows/perl-test.yml@main
    with:
      since-perl: 'v5.12.0'
      with-devel: true
      coverage: true
